# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod download

env:
  - CGO_ENABLED=0

builds:
  - main: ./cmd/apiserver
    id: "apiserver"
    binary: "apiserver"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/flowline/pkg/util/version.Version={{ .Version }}
        -X github.com/tsundata/flowline/pkg/util/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/flowline/pkg/util/version.BuildTime={{ .Timestamp }}
        #-X github.com/tsundata/flowline/pkg/util/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/controller-manager
    id: "controller-manager"
    binary: "controller-manager"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/flowline/pkg/util/version.Version={{ .Version }}
        -X github.com/tsundata/flowline/pkg/util/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/flowline/pkg/util/version.BuildTime={{ .Timestamp }}
        #-X github.com/tsundata/flowline/pkg/util/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/scheduler
    id: "scheduler"
    binary: "scheduler"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/flowline/pkg/util/version.Version={{ .Version }}
        -X github.com/tsundata/flowline/pkg/util/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/flowline/pkg/util/version.BuildTime={{ .Timestamp }}
        #-X github.com/tsundata/flowline/pkg/util/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

  - main: ./cmd/worker
    id: "worker"
    binary: "worker"
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/tsundata/flowline/pkg/util/version.Version={{ .Version }}
        -X github.com/tsundata/flowline/pkg/util/version.GitCommit={{ .ShortCommit }}
        -X github.com/tsundata/flowline/pkg/util/version.BuildTime={{ .Timestamp }}
        #-X github.com/tsundata/flowline/pkg/util/version.GoVersion={{ replace .Env.GOVERSION " " "_" }}

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^test:'
      - '^merge:'
      - '^Merge pull request'
      - '^Merge branch'
      - '^debug:'
      - '^ci:'

env_files:
  github_token: ~/.gh_token

release:
  github:
    owner: tsundata
    name: flowline
  name_template: "{{.Tag}}"
