name: Docker

on:
  push:
    tags:
      - v*
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Github tag
        id: meta
        run: |
          echo "::set-output name=tag::$(git describe --always --tags --match='v*')"

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          install-only: true

      - name: Build
        run: GOVERSION=`go version` goreleaser --snapshot --skip-publish --rm-dist

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.IMAGE_USER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push apiserver
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: build/apiserver/Dockerfile
          tags: |
            ghcr.io/${{ secrets.IMAGE_USER }}/apiserver:${{ steps.meta.outputs.tag }}

      - name: Build and push controller-manager
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: build/controller-manager/Dockerfile
          tags: |
            ghcr.io/${{ secrets.IMAGE_USER }}/controller-manager:${{ steps.meta.outputs.tag }}

      - name: Build and push scheduler
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: build/scheduler/Dockerfile
          tags: |
            ghcr.io/${{ secrets.IMAGE_USER }}/scheduler:${{ steps.meta.outputs.tag }}

      - name: Build and push worker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: build/worker/Dockerfile
          tags: |
            ghcr.io/${{ secrets.IMAGE_USER }}/worker:${{ steps.meta.outputs.tag }}
