name: Go

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    services:
      etcd:
        image: bitnami/etcd:3.5.0
        env:
          ALLOW_NONE_AUTHENTICATION: yes
        ports:
          - 2379:2379
          - 2380:2380
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
