name: Release

on:
  push:
    tags:
      - v*

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: '^1.20'

      ### Lint ###

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.1

      ### Release ###

      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          install-only: true

      - name: Release
        run: GOVERSION=$(go version) goreleaser release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}